[
  {
    date: "2024-05-04",
    driver: "Петров Иван Иванович",
    finishTime: "13:00",
    from: "Минск",
    price: 25,
    to: "Гомель",
    type: "M",
    availableSeats: 25,
    travelTime: "5:00",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "08:00",
    destination: "Автовокзал Гомель,",
    departure: 'Автовокзал "Центральный"',
    destinationAddress: "Автовокзал г. Гомель, ул. Советская, 86",
    departureAddress: 'Автовокзал "Центральный", г. Минск, пр-т Независимости, 54',
  },
  {
    date: "2024-05-03",
    driver: "Сидоров Сергей Михайлович",
    finishTime: "18:30",
    from: "Гомель",
    price: 35,
    to: "Витебск",
    type: "L",
    availableSeats: 50,
    travelTime: "8:30",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "10:00",
    destination: "Автовокзал г. Витебск, пр-т Московский, 113",
    departure: "Автовокзал г. Гомель, ул. Советская, 86",
  },
  {
    date: "2024-05-03",
    driver: "Кузнецова Ольга Петровна",
    finishTime: "17:30",
    from: "Витебск",
    price: 20,
    to: "Могилев",
    type: "M",
    availableSeats: 25,
    travelTime: "3:30",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "14:00",
    destination: "Автовокзал г. Могилев, ул. Ленинская, 63",
    departure: "Автовокзал г. Витебск, пр-т Московский, 113",
  },
  {
    date: "2024-05-03",
    driver: "Новиков Николай Васильевич",
    finishTime: "20:00",
    from: "Могилев",
    price: 40,
    to: "Брест",
    type: "L",
    availableSeats: 50,
    travelTime: "11:00",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "09:00",
    destination: "Автовокзал г. Брест, ул. Советская, 60",
    departure: "Автовокзал г. Могилев, ул. Ленинская, 63",
  },
  {
    date: "2024-05-03",
    driver: "Коржун Василиса Витальевна",
    finishTime: "15:30",
    from: "Гродно",
    price: 27,
    to: "Бобруйск",
    type: "M",
    availableSeats: 25,
    travelTime: "4:30",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "11:00",
    destination: "Автовокзал г. Бобруйск, ул. Интернациональная, 32",
    departure: "Автовокзал г. Гродно, ул. 17 Сентября, 2",
  },
  {
    date: "2024-05-03",
    driver: "Генисев Никита Андреевич",
    finishTime: "17:00",
    from: "Мозырь",
    price: 32,
    to: "Полоцк",
    type: "L",
    availableSeats: 50,
    travelTime: "9:00",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "08:00",
    destination: "Автовокзал г. Полоцк, ул. Октябрьская, 84",
    departure: "Автовокзал г. Мозырь, ул. Промышленная, 15",
  },
  {
    date: "2024-05-03",
    driver: "Дружный Валентин Витальевич",
    finishTime: "15:30",
    from: "Жлобин",
    price: 18,
    to: "Лида",
    type: "M",
    availableSeats: 25,
    travelTime: "2:30",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "13:00",
    destination: "Автовокзал г. Лида, ул. Советская, 86",
    departure: "Автовокзал г. Жлобин, ул. Пролетарская, 6",
  },
  {
    date: "2024-05-03",
    driver: "Голубочкин Дмитрий Антонович",
    finishTime: "11:30",
    from: "Марьина Горка",
    price: 12,
    to: "Дзержинск",
    type: "M",
    availableSeats: 25,
    travelTime: "1:30",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "10:00",
    destination: "Автовокзал г. Дзержинск, ул. Космонавтов, 1",
    departure: "Автовокзал г. Марьина Горка, ул. Ленинская, 2",
  },
  {
    date: "2024-05-03",
    driver: "Глянцев Василий Петрович",
    finishTime: "15:30",
    from: "Столбцы",
    price: 15,
    to: "Клецк",
    type: "M",
    availableSeats: 25,
    travelTime: "1:30",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "14:00",
    destination: "Автовокзал г. Клецк, ул. Первомайская, 15",
    departure: "Автовокзал г. Столбцы, ул. Ленина, 10",
  },
  {
    date: "2024-05-03",
    driver: "Митрин Александр Геннадьевич",
    finishTime: "10:30",
    from: "Солигорск",
    price: 14,
    to: "Несвиж",
    type: "M",
    availableSeats: 25,
    travelTime: "1 час 30 минут",
    reservedSeats: 0,
    seats: [
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
      { orderId: "", available: true, user: null, owner: null },
    ],
    startTime: "09:00",
    destination: "Автовокзал г. Несвиж, ул. Ленинская, 56",
    departure: "Автовокзал г. Солигорск, ул. Ленина, 22",
  },
]
