[
    {
      "date": "2024-01-01",
      "driver": "Александр",
      "finishTime": "23:36",
      "from": "Минск",
      "price": 8.01,
      "time": "19:36",
      "to": "Гомель",
      "tripID": 1,
      "type": "Большой",
      "availableSeats": 50,
      "travelTime": "4",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        },
        '26':{
            'available':true,
            'owner':null
        },
        '27':{
            'available':true,
            'owner':null
        },
        '28':{
            'available':true,
            'owner':null
        },
        '29':{
            'available':true,
            'owner':null
        },
        '30':{
            'available':true,
            'owner':null
        },
        '31':{
            'available':true,
            'owner':null
        },
        '32':{
            'available':true,
            'owner':null
        },
        '33':{
            'available':true,
            'owner':null
        },
        '34':{
            'available':true,
            'owner':null
        },
        '35':{
            'available':true,
            'owner':null
        },
        '36':{
            'available':true,
            'owner':null
        },
        '37':{
            'available':true,
            'owner':null
        },
        '38':{
            'available':true,
            'owner':null
        },
        '39':{
            'available':true,
            'owner':null
        },
        '40':{
            'available':true,
            'owner':null
        },
        '41':{
            'available':true,
            'owner':null
        },
        '42':{
            'available':true,
            'owner':null
        },
        '43':{
            'available':true,
            'owner':null
        },
        '44':{
            'available':true,
            'owner':null
        },
        '45':{
            'available':true,
            'owner':null
        },
        '46':{
            'available':true,
            'owner':null
        },
        '47':{
            'available':true,
            'owner':null
        },
        '48':{
            'available':true,
            'owner':null
        },
        '49':{
            'available':true,
            'owner':null
        },
        '50':{
            'available':true,
            'owner':null
        },
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Никита",
      "finishTime": "15:20",
      "from": "Гродно",
      "price": 8.66,
      "time": "12:00",
      "to": "Могилёв",
      "tripID": 2,
      "type": "Средний",
      "availableSeats": 25,
      "travelTime": "3:20",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        }
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Алексей",
      "finishTime": "19:47",
      "from": "Бобруйск",
      "price": 5.84,
      "time": "17:23",
      "to": "Барановичи",
      "tripID": 3,
      "type": "Большой",
      "availableSeats": 50,
      "travelTime": "2:24",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        },
        '26':{
            'available':true,
            'owner':null
        },
        '27':{
            'available':true,
            'owner':null
        },
        '28':{
            'available':true,
            'owner':null
        },
        '29':{
            'available':true,
            'owner':null
        },
        '30':{
            'available':true,
            'owner':null
        },
        '31':{
            'available':true,
            'owner':null
        },
        '32':{
            'available':true,
            'owner':null
        },
        '33':{
            'available':true,
            'owner':null
        },
        '34':{
            'available':true,
            'owner':null
        },
        '35':{
            'available':true,
            'owner':null
        },
        '36':{
            'available':true,
            'owner':null
        },
        '37':{
            'available':true,
            'owner':null
        },
        '38':{
            'available':true,
            'owner':null
        },
        '39':{
            'available':true,
            'owner':null
        },
        '40':{
            'available':true,
            'owner':null
        },
        '41':{
            'available':true,
            'owner':null
        },
        '42':{
            'available':true,
            'owner':null
        },
        '43':{
            'available':true,
            'owner':null
        },
        '44':{
            'available':true,
            'owner':null
        },
        '45':{
            'available':true,
            'owner':null
        },
        '46':{
            'available':true,
            'owner':null
        },
        '47':{
            'available':true,
            'owner':null
        },
        '48':{
            'available':true,
            'owner':null
        },
        '49':{
            'available':true,
            'owner':null
        },
        '50':{
            'available':true,
            'owner':null
        },
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Владислав",
      "finishTime": "16:50",
      "from": "Мозырь",
      "price": 4.76,
      "time": "13:30",
      "to": "Брест",
      "tripID": 4,
      "type": "Большой",
      "availableSeats": 50,
      "travelTime": "3:20",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        },
        '26':{
            'available':true,
            'owner':null
        },
        '27':{
            'available':true,
            'owner':null
        },
        '28':{
            'available':true,
            'owner':null
        },
        '29':{
            'available':true,
            'owner':null
        },
        '30':{
            'available':true,
            'owner':null
        },
        '31':{
            'available':true,
            'owner':null
        },
        '32':{
            'available':true,
            'owner':null
        },
        '33':{
            'available':true,
            'owner':null
        },
        '34':{
            'available':true,
            'owner':null
        },
        '35':{
            'available':true,
            'owner':null
        },
        '36':{
            'available':true,
            'owner':null
        },
        '37':{
            'available':true,
            'owner':null
        },
        '38':{
            'available':true,
            'owner':null
        },
        '39':{
            'available':true,
            'owner':null
        },
        '40':{
            'available':true,
            'owner':null
        },
        '41':{
            'available':true,
            'owner':null
        },
        '42':{
            'available':true,
            'owner':null
        },
        '43':{
            'available':true,
            'owner':null
        },
        '44':{
            'available':true,
            'owner':null
        },
        '45':{
            'available':true,
            'owner':null
        },
        '46':{
            'available':true,
            'owner':null
        },
        '47':{
            'available':true,
            'owner':null
        },
        '48':{
            'available':true,
            'owner':null
        },
        '49':{
            'available':true,
            'owner':null
        },
        '50':{
            'available':true,
            'owner':null
        },
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Андрей",
      "finishTime": "11:05",
      "from": "Кричев",
      "price": 4.42,
      "time": "09:45",
      "to": "Костюковичи",
      "tripID": 5,
      "type": "Средний",
      "availableSeats": 25,
      "travelTime": "1:20",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        }
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Дмитрий",
      "finishTime": "19:40",
      "from": "Браслав",
      "price": 2.37,
      "time": "18:20",
      "to": "Докшицы",
      "tripID": 6,
      "type": "Большой",
      "availableSeats": 50,
      "travelTime": "1:20",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        },
        '26':{
            'available':true,
            'owner':null
        },
        '27':{
            'available':true,
            'owner':null
        },
        '28':{
            'available':true,
            'owner':null
        },
        '29':{
            'available':true,
            'owner':null
        },
        '30':{
            'available':true,
            'owner':null
        },
        '31':{
            'available':true,
            'owner':null
        },
        '32':{
            'available':true,
            'owner':null
        },
        '33':{
            'available':true,
            'owner':null
        },
        '34':{
            'available':true,
            'owner':null
        },
        '35':{
            'available':true,
            'owner':null
        },
        '36':{
            'available':true,
            'owner':null
        },
        '37':{
            'available':true,
            'owner':null
        },
        '38':{
            'available':true,
            'owner':null
        },
        '39':{
            'available':true,
            'owner':null
        },
        '40':{
            'available':true,
            'owner':null
        },
        '41':{
            'available':true,
            'owner':null
        },
        '42':{
            'available':true,
            'owner':null
        },
        '43':{
            'available':true,
            'owner':null
        },
        '44':{
            'available':true,
            'owner':null
        },
        '45':{
            'available':true,
            'owner':null
        },
        '46':{
            'available':true,
            'owner':null
        },
        '47':{
            'available':true,
            'owner':null
        },
        '48':{
            'available':true,
            'owner':null
        },
        '49':{
            'available':true,
            'owner':null
        },
        '50':{
            'available':true,
            'owner':null
        },
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Антон",
      "finishTime": "16:56",
      "from": "Шклов",
      "price": 4.42,
      "time": "15:20",
      "to": "Славгород",
      "tripID": 7,
      "type": "Средний",
      "availableSeats": 25,
      "travelTime": "1:36",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        }
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Игорь",
      "finishTime": "13:10",
      "from": "Чаусы",
      "price": 4.13,
      "time": "11:10",
      "to": "Мстиславль",
      "tripID": 8,
      "type": "Средний",
      "availableSeats": 25,
      "travelTime": "2",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        }
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Максим",
      "finishTime": "08:50",
      "from": "Минск",
      "price": 10.06,
      "time": "07:30",
      "to": "Толочин",
      "tripID": 9,
      "type": "Маленький",
      "availableSeats": 15,
      "travelTime": "1:20",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        }
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Сергей",
      "finishTime": "09:51",
      "from": "Орша",
      "price": 4.42,
      "time": "08:15",
      "to": "Логойск",
      "tripID": 10,
      "type": "Средний",
      "availableSeats": 25,
      "travelTime": "1:36",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        }
      }
    },
    {
      "date": "2024-01-01",
      "driver": "Виктор",
      "finishTime": "21:00",
      "from": "Минск",
      "price": 4.76,
      "time": "19:00",
      "to": "Верхнедвинск",
      "tripID": 11,
      "type": "Большой",
      "availableSeats": 50,
      "travelTime": "2",
      "reservedSeats": 0,
      "seats": {
        '1':{
            'available':true,
            'owner':null
        },
        '2':{
            'available':true,
            'owner':null
        },
        '3':{
            'available':true,
            'owner':null
        },
        '4':{
            'available':true,
            'owner':null
        },
        '5':{
            'available':true,
            'owner':null
        },
        '6':{
            'available':true,
            'owner':null
        },
        '7':{
            'available':true,
            'owner':null
        },
        '8':{
            'available':true,
            'owner':null
        },
        '9':{
            'available':true,
            'owner':null
        },
        '10':{
            'available':true,
            'owner':null
        },
        '11':{
            'available':true,
            'owner':null
        },
        '12':{
            'available':true,
            'owner':null
        },
        '13':{
            'available':true,
            'owner':null
        },
        '14':{
            'available':true,
            'owner':null
        },
        '15':{
            'available':true,
            'owner':null
        },
        '16':{
            'available':true,
            'owner':null
        },
        '17':{
            'available':true,
            'owner':null
        },
        '18':{
            'available':true,
            'owner':null
        },
        '19':{
            'available':true,
            'owner':null
        },
        '20':{
            'available':true,
            'owner':null
        },
        '21':{
            'available':true,
            'owner':null
        },
        '22':{
            'available':true,
            'owner':null
        },
        '23':{
            'available':true,
            'owner':null
        },
        '24':{
            'available':true,
            'owner':null
        },
        '25':{
            'available':true,
            'owner':null
        },
        '26':{
            'available':true,
            'owner':null
        },
        '27':{
            'available':true,
            'owner':null
        },
        '28':{
            'available':true,
            'owner':null
        },
        '29':{
            'available':true,
            'owner':null
        },
        '30':{
            'available':true,
            'owner':null
        },
        '31':{
            'available':true,
            'owner':null
        },
        '32':{
            'available':true,
            'owner':null
        },
        '33':{
            'available':true,
            'owner':null
        },
        '34':{
            'available':true,
            'owner':null
        },
        '35':{
            'available':true,
            'owner':null
        },
        '36':{
            'available':true,
            'owner':null
        },
        '37':{
            'available':true,
            'owner':null
        },
        '38':{
            'available':true,
            'owner':null
        },
        '39':{
            'available':true,
            'owner':null
        },
        '40':{
            'available':true,
            'owner':null
        },
        '41':{
            'available':true,
            'owner':null
        },
        '42':{
            'available':true,
            'owner':null
        },
        '43':{
            'available':true,
            'owner':null
        },
        '44':{
            'available':true,
            'owner':null
        },
        '45':{
            'available':true,
            'owner':null
        },
        '46':{
            'available':true,
            'owner':null
        },
        '47':{
            'available':true,
            'owner':null
        },
        '48':{
            'available':true,
            'owner':null
        },
        '49':{
            'available':true,
            'owner':null
        },
        '50':{
            'available':true,
            'owner':null
        },
      }
    }
  ]
  